### ISSUE TITLE
PAN Adapter GUI

### ISSUE THREAD

**Issue by bqc0n** [TRCDevelopers/Clayium#198]
![image](https://github.com/user-attachments/assets/97806f8c-3704-4138-bb48-173e07727b48)

**Comment by SoldierFace** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
