### ISSUE TITLE
BUG: 粘土樹作成に必要なエネルギー値が高い

### ISSUE THREAD

**Issue by Amai-ICE** [TRCDevelopers/Clayium#226]
https://github.com/TRCDevelopers/Clayium/blob/84c5b1c9868781fccc78b6aba2bb9640d48a6c31/src/main/kotlin/com/github/trc/clayium/api/capability/impl/ClayLaserIrradiator.kt#L82

https://github.com/TRCDevelopers/Clayium/blob/84c5b1c9868781fccc78b6aba2bb9640d48a6c31/src/main/resources/assets/clayium/lang/ja_jp.lang#L246
JEI上では1000と表示されているのにもかかわらず、実際には10000のエネルギー値が必要になっている

**Comment by soramame0256** [comment]
報告ありがとうございます。
