### ISSUE TITLE
BUG: 粘土分配器を使用するとアイテムが増殖する

### ISSUE THREAD

**Issue by Amai-ICE** [TRCDevelopers/Clayium#227]
分配器を使用してアイテムを均等分割した際にアイテムが増殖する
![Screenshot_20241005_044226](https://github.com/user-attachments/assets/9a069df7-b56e-4902-bb89-db1bf93ad41f)
この様に配置して前後で比較すると

前
![image](https://github.com/user-attachments/assets/95d21c4b-0ffb-4c72-98d3-e386931440f3)

後
![image](https://github.com/user-attachments/assets/98be3065-e0cc-42eb-a1d1-a3eeaa5509ee)

**Comment by soramame0256** [comment]
報告ありがとうございます。
