### ISSUE TITLE
BUG: 粘土分配機の搬出量は実質的にどれも一定である

### ISSUE THREAD

**Issue by Amai-ICE** [TRCDevelopers/Clayium#236]
粘土分配機のリミットはそれぞれの機械の最大搬出を参照しているが、
![image](https://github.com/user-attachments/assets/f59e1902-4f41-4436-98dd-6bed158a0de6)

この様に配置した際には最大搬出力は全て256item(4st)/cycleとなっている

**Comment by soramame0256** [comment]
報告ありがとうございます。

**Comment by bqc0n** [comment]
fixed in #244
