### ISSUE TITLE
GroovyScript compatibility

### ISSUE THREAD

**Issue by code-onigiri** [TRCDevelopers/Clayium#253]
### Mod Version

1.0.0-beta4

### Your Solution

As the title says
I might do it myself.

**Comment by bqc0n** [comment]
あまり深くテストしていませんが、GrSでのレシピ追加であれば既に可能です。https://bqc0n.github.io/clayium-wiki/groovy-script/recipe.html

**Comment by code-onigiri** [comment]
あっ...気づかなかった...
良さそうですありがとうございます！！！！！！
