### ISSUE TITLE
ModularUIのv2.5.0-rc2(CleanroomMC)ではGUIが開けない

### ISSUE THREAD

**Issue by sekinon-maru9** [TRCDevelopers/Clayium#262]
### Mod Version

0.4.1

### Environment

Cleanroom環境、シングルプレイ

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

機械を右クリックするとGUIが開かれる

### Actual Behavior

[ModularUIのv2.5.0-rc2](https://github.com/CleanroomMC/ModularUI/releases/tag/v2.5.0-rc2)を導入している場合、機械を右クリックしてもGUIが開かない（記入済みの看板(modなし)と同じ挙動になる）

### Steps to Reproduce

[ModularUIのv2.5.0-rc2](https://github.com/CleanroomMC/ModularUI/releases/tag/v2.5.0-rc2)を導入すると再現可能

**Comment by bqc0n** [comment]
報告ありがとうございます。
ModularUI 2.4.3と2.5.0-rc2では内部構造に大きな変更があり、互換性がありません。
現在、Modrinth/CurseForgeで公開されている最新のバージョンは2.4.3なので、2.5.0が正式リリースされるまでは、申し訳ありませんが2.4.3を利用してください。
